@startuml

[*] --> 壁判定 : 何かに触れた
壁判定 -->  [*]

state 壁判定{
[*] --> 接触対象の判定
接触対象の判定 --> 接触状態を接触中に変更 : 壁である
接触状態を接触中に変更 : entry / 状態を壁接触状態に変更する
接触対象の判定 --> [*] : 壁でない
接触状態を接触中に変更 --> [*]
}

[*] --> 高速移動処理 : 周期開始時
高速移動処理 -->  [*]

state 高速移動処理 {
[*] --> 壁接触状態の判定
壁接触状態の判定 --> 入力を受け付ける : 壁非接触状態
壁接触状態の判定 --> 入力を受け付けない : 壁接触状態

入力を受け付ける --> 高速移動 : キー入力されている
高速移動 : entry / 状態を高速移動中にする
高速移動 --> [*]
入力を受け付ける --> [*] : キー入力されていない
入力を受け付けない --> [*]
入力を受け付けない : entry / 状態を非高速移動中に変更する
}


@enduml