@startuml
skin rose
start

:お腹具合を調査する;
if (お腹具合状態) then (とてもすいている)
    :ご飯を食べる;
    :状態をお腹がすいていないに変更;
else if(お腹具合状態) then (すこしすいている)
    :おやつを食べる;
    :状態をお腹がすいていないに変更;
else (お腹がすいていない)
    :なにもしない;
endif

end
@enduml